sonar.projectKey=fullstack-notes-app
sonar.projectName=FullStack Notes App
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.spec.js,**/*.test.js,coverage/**,frontend/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://localhost:9000
sonar.token=sqp_14bda462968aa36618ba5a357385a129288ac257